name: easy_timer_count
description: "A flexible Flutter package for countdown and count-up timers"
version: 0.0.1
repository: https://github.com/ahmedemara231/easy_timer_count
homepage: https://github.com/ahmedemara231/easy_timer_count

topics:
  - timer
  - stopwatch
  - countup
  - countdown
  - time

environment:
  sdk: '>=3.2.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter_screenutil: ^5.9.3
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter: